import React, { createContext, useContext, useEffect, useState } from "react";

export type Lang = "ru" | "en" | "uz";

const translations: Record<Lang, Record<string, string>> = {
  ru: {
    title: "Adamant Solar",
    subtitle: "Создайте ваш заказ на солнечные панели",
    sign_in: "Войти",
    signing_in: "Вход...",
    create_order: "Создать заказ",
    sign_out: "Выйти",
    profile: "Профиль",
    balance: "Баланс",
    currency: "сум",
    top_up: "Пополнить",
    top_up_soon: "Пополнение появится скоро",
    top_up_via_uzum: "Пополнение через Uzum Bank",
    uzum_top_up_description: "Выберите сумму и способ оплаты. Сейчас это только UI-заготовка.",
    uzum_ready_for_payment: "Быстрое пополнение баланса",
    top_up_amount: "Сумма пополнения",
    uzum_payment_method: "Оплата через Uzum Bank",
    selected: "Выбрано",
    continue_to_uzum: "Продолжить",
    top_up_title: "Пополнение баланса",
    top_up_choose: "Выберите способ оплаты и сумму",
    payment_method: "Способ оплаты",
    proceed_to_payment: "Перейти к оплате",
    redirecting_to: "Переход к оплате через",
    pm_uzum_desc: "Оплата картой Uzum Bank",
    pm_payme_desc: "Оплата через Payme",
    pm_click_desc: "Оплата через Click",
    pm_oxapay_desc: "Оплата криптовалютой",
    copy_ref_link: "Скопировать реф-ссылку",
    ref_link_copied: "Реф-ссылка скопирована",
    language: "Язык",
    location_label: "Город, Страна",
    location_placeholder: "Город, Страна",
    delivery_address: "Адрес доставки",
    contact_number: "Контактный номер",
    main_title_required: "Требуется заголовок",
    line1_required: "Требуется строка 1",
    line2_required: "Требуется строка 2",
    delivery_address_required: "Требуется адрес доставки",
    contact_number_required: "Требуется контактный номер",
    location_required: "Пожалуйста, выберите город из списка",
    tashkent_error: "Адрес должен быть в Ташкенте",
    delivery_address_hint: "Укажите полный адрес в Ташкенте для доставки",
    contact_placeholder: "+998 90 123 45 67",
    login_description: "Войдите, чтобы начать",
    terms_notice: "При входе вы соглашаетесь с Условиями обслуживания и Политикой конфиденциальности",
    tab_buy: "Купить",
    tab_orders: "Заказы",
    step_order_details: "Шаг 1: детали заказа",
    step_delivery_address: "Шаг 2: адрес доставки",
    currently_available_tashkent: "Выберите город звездного неба",
    day: "День",
    month: "Месяц",
    year: "Год",
    hide_time_output: "Скрыть время в заказе",
    hour: "Час",
    minute: "Минута",
    main_title_label: "Заголовок",
    line1_label: "Строка 1",
    line2_label: "Строка 2",
    message_optional: "Сообщение (необязательно)",
    continue_to_address: "Перейти к адресу",
    delivery_address_placeholder: "Введите адрес доставки в Ташкенте...",
    order_summary: "Сводка заказа",
    product_type: "Тип продукта",
    size_small: "Маленький",
    size_medium: "Средний",
    size_large: "Большой",
    price_label: "Цена",
    order_placed_success: "Заказ оформлен и оплачен",
    order_failed: "Не удалось оформить заказ. Попробуйте ещё раз",
    insufficient_balance: "Недостаточно средств на балансе. Пополните счёт",
    title_label: "Заголовок",
    date_label: "Дата",
    time_label: "Время",
    back: "Назад",
    placing_order: "Отправка заказа...",
    place_order: "Оформить заказ",
    your_orders: "Ваши заказы",
    track_manage_orders: "Отслеживайте и управляйте вашими заказами на солнечные панели",
    new_order: "Новый заказ",
    no_orders_yet: "Пока нет заказов",
    create_first_order: "Создать первый заказ",
    order_number: "Заказ",
    created_label: "Создан",
    message_label: "Сообщение",
    status_pending: "Ожидает",
    status_processing: "Обрабатывается",
    status_completed: "Выполнен",
    status_cancelled: "Отменён",
    main_title_placeholder: "Например, Вдохновлён звёздами",
    line1_placeholder: "Например, Звёздное небо над",
    line2_placeholder: "Например, Вашим районом",
    message_placeholder: "Добавьте необязательное сообщение...",
  },
  en: {
    title: "Adamant Solar",
    subtitle: "Create your custom solar panel order",
    sign_in: "Sign In",
    signing_in: "Signing in...",
    create_order: "Create Order",
    sign_out: "Sign Out",
    profile: "Profile",
    balance: "Balance",
    currency: "UZS",
    top_up: "Top up",
    top_up_soon: "Top-up is coming soon",
    top_up_via_uzum: "Top up via Uzum Bank",
    uzum_top_up_description: "Choose the amount and payment method. This is UI-only for now.",
    uzum_ready_for_payment: "Fast balance top-up",
    top_up_amount: "Top-up amount",
    uzum_payment_method: "Payment via Uzum Bank",
    selected: "Selected",
    continue_to_uzum: "Continue",
    top_up_title: "Top up balance",
    top_up_choose: "Choose a payment method and amount",
    payment_method: "Payment method",
    proceed_to_payment: "Proceed to payment",
    redirecting_to: "Redirecting to",
    pm_uzum_desc: "Pay with Uzum Bank card",
    pm_payme_desc: "Pay via Payme",
    pm_click_desc: "Pay via Click",
    pm_oxapay_desc: "Pay with crypto",
    copy_ref_link: "Copy referral link",
    ref_link_copied: "Referral link copied",
    language: "Language",
    location_label: "City, Country",
    location_placeholder: "City, Country",
    delivery_address: "Delivery Address",
    contact_number: "Contact number",
    main_title_required: "Main title is required",
    line1_required: "Line 1 is required",
    line2_required: "Line 2 is required",
    delivery_address_required: "Delivery address is required",
    contact_number_required: "Contact number is required",
    location_required: "Please select a city from the list",
    tashkent_error: "Delivery address must be in Tashkent",
    delivery_address_hint: "Please provide a complete address in Tashkent for delivery",
    contact_placeholder: "+998 90 123 45 67",
    login_description: "Sign in to get started",
    terms_notice: "By signing in, you agree to our Terms of Service and Privacy Policy",
    tab_buy: "Buy",
    tab_orders: "Orders",
    step_order_details: "Step 1: Order Details",
    step_delivery_address: "Step 2: Delivery Address",
    currently_available_tashkent: "Select the city of the starry sky",
    day: "Day",
    month: "Month",
    year: "Year",
    hide_time_output: "Hide time on output",
    hour: "Hour",
    minute: "Minute",
    main_title_label: "Main Title",
    line1_label: "Line 1",
    line2_label: "Line 2",
    message_optional: "Message (Optional)",
    continue_to_address: "Continue to Address",
    delivery_address_placeholder: "Enter your delivery address in Tashkent...",
    order_summary: "Order Summary",
    product_type: "Product type",
    size_small: "Small",
    size_medium: "Medium",
    size_large: "Large",
    price_label: "Price",
    order_placed_success: "Order placed and paid",
    order_failed: "Failed to place order. Please try again",
    insufficient_balance: "Insufficient balance. Please top up your account",
    title_label: "Title",
    date_label: "Date",
    time_label: "Time",
    back: "Back",
    placing_order: "Placing Order...",
    place_order: "Place Order",
    your_orders: "Your Orders",
    track_manage_orders: "Track and manage your solar panel orders",
    new_order: "New Order",
    no_orders_yet: "No orders yet",
    create_first_order: "Create Your First Order",
    order_number: "Order",
    created_label: "Created",
    message_label: "Message",
    status_pending: "Pending",
    status_processing: "Processing",
    status_completed: "Completed",
    status_cancelled: "Cancelled",
    main_title_placeholder: "e.g., Written in the stars",
    line1_placeholder: "e.g., The starry sky over",
    line2_placeholder: "e.g., Your location name",
    message_placeholder: "Add an optional message...",
  },
  uz: {
    title: "Adamant Solar",
    subtitle: "Quyosh panellari buyurtmangizni yarating",
    sign_in: "Kirish",
    signing_in: "Kirish...",
    create_order: "Buyurtma yaratish",
    sign_out: "Chiqish",
    profile: "Profil",
    balance: "Balans",
    currency: "so'm",
    top_up: "To'ldirish",
    top_up_soon: "To'ldirish tez orada",
    top_up_via_uzum: "Uzum Bank orqali to'ldirish",
    uzum_top_up_description: "Summani va to'lov usulini tanlang. Hozircha bu faqat UI.",
    uzum_ready_for_payment: "Balansni tez to'ldirish",
    top_up_amount: "To'ldirish summasi",
    uzum_payment_method: "Uzum Bank orqali to'lov",
    selected: "Tanlandi",
    continue_to_uzum: "Davom etish",
    top_up_title: "Balansni to'ldirish",
    top_up_choose: "To'lov usulini va summani tanlang",
    payment_method: "To'lov usuli",
    proceed_to_payment: "To'lovga o'tish",
    redirecting_to: "To'lovga o'tilmoqda:",
    pm_uzum_desc: "Uzum Bank kartasi bilan to'lov",
    pm_payme_desc: "Payme orqali to'lov",
    pm_click_desc: "Click orqali to'lov",
    pm_oxapay_desc: "Kripto bilan to'lov",
    copy_ref_link: "Referal havolani nusxalash",
    ref_link_copied: "Referal havola nusxalandi",
    language: "Til",
    location_label: "Shahar, Mamlakat",
    location_placeholder: "Shahar, Mamlakat",
    delivery_address: "Yetkazib berish manzili",
    contact_number: "Aloqa raqami",
    main_title_required: "Sarlavha talab qilinadi",
    line1_required: "1-qator talab qilinadi",
    line2_required: "2-qator talab qilinadi",
    delivery_address_required: "Yetkazib berish manzili talab qilinadi",
    contact_number_required: "Aloqa raqami talab qilinadi",
    location_required: "Iltimos, ro'yxatdan shaharni tanlang",
    tashkent_error: "Yetkazib berish manzili Toshkentda bo'lishi kerak",
    delivery_address_hint: "Iltimos, yetkazib berish uchun Toshkentdagi to'liq manzilni kiriting",
    contact_placeholder: "+998 90 123 45 67",
    login_description: "Boshlash uchun tizimga kiring",
    terms_notice: "Tizimga kirish orqali siz Foydalanish shartlari va Maxfiylik siyosati bilan rozilasiz",
    tab_buy: "Sotib olish",
    tab_orders: "Buyurtmalar",
    step_order_details: "1-qadam: buyurtma tafsilotlari",
    step_delivery_address: "2-qadam: yetkazib berish manzili",
    currently_available_tashkent: "Yulduzli osmon shahrini tanlang",
    day: "Kun",
    month: "Oy",
    year: "Yil",
    hide_time_output: "Vaqtni yashirish",
    hour: "Soat",
    minute: "Daqiqa",
    main_title_label: "Sarlavha",
    line1_label: "1-qator",
    line2_label: "2-qator",
    message_optional: "Xabar (ixtiyoriy)",
    continue_to_address: "Manzilga o‘tish",
    delivery_address_placeholder: "Toshkentdagi yetkazib berish manzilini kiriting...",
    order_summary: "Buyurtma xulosasi",
    product_type: "Mahsulot turi",
    size_small: "Kichik",
    size_medium: "O'rta",
    size_large: "Katta",
    price_label: "Narxi",
    order_placed_success: "Buyurtma rasmiylashtirildi va to'landi",
    order_failed: "Buyurtma berilmadi. Qaytadan urinib ko'ring",
    insufficient_balance: "Balansda mablag' yetarli emas. Hisobni to'ldiring",
    title_label: "Sarlavha",
    date_label: "Sana",
    time_label: "Vaqt",
    back: "Orqaga",
    placing_order: "Buyurtma yuborilmoqda...",
    place_order: "Buyurtmani yuborish",
    your_orders: "Sizning buyurtmalaringiz",
    track_manage_orders: "Quyosh panellari buyurtmalarini kuzatib boring va boshqaring",
    new_order: "Yangi buyurtma",
    no_orders_yet: "Hali buyurtma yo'q",
    create_first_order: "Birinchi buyurtmani yarating",
    order_number: "Buyurtma",
    created_label: "Yaratildi",
    message_label: "Xabar",
    status_pending: "Kutmoqda",
    status_processing: "Jarayon",
    status_completed: "Yakunlandi",
    status_cancelled: "Bekor qilindi",
    main_title_placeholder: "Masalan, Yulduzlar ilhomlantirgan",
    line1_placeholder: "Masalan, Yulduzli osmon ustida",
    line2_placeholder: "Masalan, Sizning joyingiz",
    message_placeholder: "Ixtiyoriy xabar qo'shing...",
  },
};

const LanguageContext = createContext({
  lang: "ru" as Lang,
  t: (key: string) => key,
  setLang: (l: Lang) => {},
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>(() => {
    try {
      const stored = localStorage.getItem("lang");
      return (stored as Lang) || "ru";
    } catch {
      return "ru";
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem("lang", lang);
    } catch {}
  }, [lang]);

  const t = (key: string) => translations[lang][key] ?? key;
  const contextValue = { lang, t, setLang };

  return <LanguageContext.Provider value={contextValue}>{children}</LanguageContext.Provider>;
};

export function useLanguage() {
  return useContext(LanguageContext);
}